[tool.poetry]
name = "repl_python3_RPG-Game-Myles-1"
version = "0.1.0"
description = ""
authors = ["AirMyles <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
